//
//  ExperienceData.swift
//  SanDiegoZooSample
//
//  Created by Wilson Desimini on 3/12/19.
//  Copyright © 2019 Wilson Desimini. All rights reserved.
//

import UIKit

private let justCall: String = "Call to make reservations"

struct ZooExperiences {
    static let specialExperiences = [
        SpecialExperience(imageString: "Inside Look Tours_TN",
                          title: "Inside Look Tours",
                          description: "The Inside Look Tour is a two-hour entertaining and educational adventure offering special behind-the-scenes views and interesting information about how we take care of our animals. It is filled with experiences and stories you can’t get anywhere else. You’ll be part of a small group traveling the Zoo on foot and in a shuttle cart visiting off-exhibit areas. See the Zoo the way everyone wishes they could—from behind the scenes! Which Inside Look will you choose?",
                          times: "Offered daily",
                          duration: "2 hours",
                          ageInterest: "Adults, Kids, Teens, Seniors",
                          price: "$89 & up",
                          ticketsURL: "https://tickets.sandiegozoo.org/webstore/shop/ViewItems.aspx?CG=webstoresdz&C=sdzil"),
        SpecialExperience(imageString: "Wild Night Out (21+)_TN",
                          title: "Wild Night Out (21+)",
                          description: "Join us for an evening of music, socializing, and animal friends, and a preview of Jungle Bells at the San Diego Zoo! Adults—ages 21 and up only—can visit parts of the Zoo, savor a complimentary beverage (choice of either one beer, soda, or water), talk with a keeper, meet some animal ambassadors up close, and enjoy a variety of music and more, for a special night of fun! Reservations are required; purchase tickets online, at the Zoo, or by calling 619-718-3000. Price includes one welcome beverage voucher and admission to the event (including evening Zoo admission). Additional food and beverages available for sale at the event. Tickets are non-refundable.",
                          times: "5:30 to 9 p.m.",
                          duration: "3.5 hours",
                          ageInterest: "Adults",
                          price: "$40",
                          ticketsURL:"https://tickets.sandiegozoo.org/webstore/shop/ViewItems.aspx?CG=zwno21&C=wno"),
        SpecialExperience(imageString: "Keeper for a Day_TN",
                          title: "Keeper for a Day",
                          description: "What does it take to be a zookeeper at the San Diego Zoo? In this personalized experience, you will learn firsthand from our world-class keepers! Enjoy a brief orientation, put on your Keeper for a Day souvenir T-shirt, and head out to the animal area of your choice to meet your Keeper Guide for the day! You'll spend the next few hours shadowing a keeper as they complete the daily tasks necessary to care for our animals. You may help our keepers prepare diets, rake and clean exhibits, or create enrichment items. You will step inside animal enclosures to see the Zoo from a whole new perspective, and learn how we care for our animals—up close. Choose to shadow a giraffe keeper (Saturdays) or a koala keeper (Sundays). Each Keeper for a Day experience includes special orientation materials, a souvenir Keeper for a Day hat and T-shirt, and lunch!",
                          times: "7:30 a.m. to 12:30 p.m. on select weekends",
                          duration: "5 hours",
                          ageInterest: "Adults, Teens",
                          price: "$850",
                          ticketsURL: justCall),
        SpecialExperience(imageString: "Early Morning with Pandas_TN",
                          title: "Early Morning with Pandas",
                          description: "Here’s your chance to visit our giant panda viewing area before it officially opens for the day! This new, small-group tour starts before the Zoo opens, so you can watch pandas Xiao Liwu (pictured) and/or Bai Yun enjoying their breakfast. Get the latest info on our popular bamboo bears!\n\nEarly Morning with Pandas is a two-hour adventure that also includes a tour around the Zoo in a shuttle cart, with stops to visit some of our other animals up close. Discover how the Zoo works to accomplish its goals of wildlife conservation and education.\n\nSee the Zoo the way everyone wishes they could, starting with this special opportunity to view the pandas!",
                          times: "Daily, 8:30 to 10:30 a.m.",
                          duration: "2 hours",
                          ageInterest: "Adults, Kids, Teens, Tweens, Seniors",
                          price: "$109 & up",
                          ticketsURL:"https://tickets.sandiegozoo.org/webstore/shop/ViewItems.aspx?CG=webstoresdz&C=sdzemwp"),
        SpecialExperience(imageString: "Animals in Action_TN",
                          title: "Animals in Action",
                          description: "Meet animals up close!\n\nSee exotic cats climb and jump, feed flamingos, and much more! Bring your camera to this fun and interactive experience, as we bring the animals out to you for an up-close view. Our expert trainers will also take you behind the scenes to feed, touch, or help train some of our animal ambassadors. You will hear amazing stories about each animal you meet, and find out how the San Diego Zoo is helping to save species here and around the world. Some animals are unique to this experience and can only be viewed by attending Animals In Action!* Reserve your spot today!",
                          times: "Offered Select Days",
                          duration: "1 hour",
                          ageInterest: "Adults, Kids, Teens, Tweens, Seniors",
                          price: "$109 & up",
                          ticketsURL:"https://tickets.sandiegozoo.org/webstore/shop/viewItems.aspx?cg=webstoresdz&c=sdzaia"),
        SpecialExperience(imageString: "Crazy About Cats_TN",
                          title: "Crazy About Cats",
                          description: "Travel by cart and foot to some of the Zoo's most iconic and fascinating cat species on this early morning tour focusing on wild cats! Go behind the scenes with your tour guide for a private viewing and/or visits with some of our famous felines and other animal friends. Visit private keeper areas and learn about cats of all sizes, how our keepers care for them, and what you can do to help cat species worldwide. We cannot guarantee which animals guests will see on any particular morning, but depending on availability—always subject to change—you might see a jaguar, lion, tiger, mountain lion, fishing cat, leopard, ocelot, or serval!",
                          times: "8:30 to 10:30 a.m. on Select Days",
                          duration: "2 hours",
                          ageInterest: "Adults, Kids, Teens, Tweens, Seniors",
                          price: "$109 & up",
                          ticketsURL: "https://tickets.sandiegozoo.org/webstore/shop/viewItems.aspx?cg=webstoresdz&c=cac"),
        SpecialExperience(imageString: "Discovery Cart Tour_TN",
                          title: "Discovery Cart Tour",
                          description: "Sit back in the comfort of our expedition cart, as you enjoy a 60-minute guided tour of the Zoo led by one of our knowledgeable guides. As you explore the Zoo together, your guide will share stories about the plants and animals in our care, and how our conservation research is making an impact worldwide. The Discovery Tour route includes areas of the Zoo not seen from the Guided Bus Tour, and the small group size allows us to answer all your questions! Step off the cart for a closer look at some of your favorite critters, and snap some amazing photos, as you enjoy this unique Zoo experience. ",
                          times: "Offered daily",
                          duration: "1 hour",
                          ageInterest: "Adults, Kids, Preschoolers, Teens, Tweens, Seniors",
                          price: "$54 & up",
                          ticketsURL: "https://tickets.sandiegozoo.org/webstore/shop/viewItems.aspx?cg=webstoresdz&c=sdzdt"),
        SpecialExperience(imageString: "Sunrise Surprise Stroll_TN",
                          title: "Sunrise Surprise Stroll",
                          description: "What will you see this month? Walk the grounds with experienced Zoo educators as they share the latest updates on our animal collection and the “inside secrets” of what’s going on, all before the Zoo opens for the day. Each month is different, and you won’t know what you’ll see and learn until you get here! This is a 90-minute walking tour to areas in natural hills and valleys, and includes breakfast muffins and coffee.\n\nReservations are required prior to the stroll. Limited space is available.  Printed tickets must be presented at check-in. Check-in at the Dickinson Family Center for Lifelong Learning (formerly the Otto Center).",
                          times: "Select Saturdays and Sundays",
                          duration: "90 minutes",
                          ageInterest: "Adults, Teens, Tweens, Seniors",
                          price: "$29",
                          ticketsURL: "https://tickets.sandiegozoo.org/webstore/shop/viewItems.aspx?cg=webstoresdz&c=sdzsss"),
        SpecialExperience(imageString: "Exclusive VIP Experience_TN",
                          title: "Exclusive VIP Experience",
                          description: "The Exclusive VIP Experience is the ultimate way to experience the San Diego Zoo! Our team of professionals will customize your visit to suit your needs and interests. Looking for a journey to some of the most exclusive areas of the most famous zoo in the world? Like to get up close and personal with animal ambassadors? The Exclusive VIP Experience is your key to off-exhibit areas, animal interactions, and the very best in personalized service. Spend up to five hours exploring the Zoo with your own personal tour guide. Have more time? Spend your entire day with us (up to eight hours)! Each Exclusive VIP Experience is tailored to your interests and includes a sit-down lunch at a Zoo restaurant. All Exclusive VIP Experiences are customized to your specifications. This very popular tour requires advance reservations and upon request, is subject to availability. Please call 619-718-3000, as soon as possible to request and confirm availability. All requests must be made a minimum of 72 hours in advance. Please note: Animal presentations and behind-the-scene areas are subject to change based on the health and welfare of the animals.",
                          times: "Offered daily",
                          duration: "5-8 hours",
                          ageInterest: "Adults, Kids, Preschoolers, Teens, Tweens, Seniors",
                          price: "$690 & up",
                          ticketsURL: justCall)
    ]
    static let zooEducations = [
        ZooEducation(imageString: "Videoconferencing_TN",
                     title: "Videoconferencing",
                     description: "Videoconferences are available with San Diego Zoo educators on a variety of topics. Animal presentations by our education staff can cover several animal and conservation subjects, including:\n\nAnimal adaptations—How do an animal's body parts and habits help it survive in its environment?\n\nAnimal classifications—What is a bird, mammal, reptile, or insect?\n\nEndangered Species—What factors are threatening wild animals and plants? What can you do to help?\n\nThe science content of these presentation topics is most appropriate for school groups in grades kindergarten through six. All can be adapted for family audiences at non-school events. All videoconference programs originate from our Zoo classroom, and include animals from our animal ambassador collection. Animal ambassadors include a variety of birds, mammals, and reptiles from around the world that can be handled by Zoo educators and brought to our classroom for an up-close look on camera. The videoconference program includes a 30- to 45-minute presentation. We have the ability to do IP videoconference format (H.323) only. Reservations for videoconferences must be made at least three weeks in advance. Maximum audience is 60 students. To make a reservation or for more information, please call 619-557-3963, Mondays–Fridays, 8 a.m.–4 p.m.",
                     times: "Tuesdays through Thursdays, beginning no earlier than 7:30 a.m. Pacific Time.",
                     duration: "30-45 minutes",
                     ageInterest: "Kids, Teens, Tweens",
                     price: "$129",
                     ticketsURL: justCall),
        ZooEducation(title: "Wildlife Sleepovers",
                     description: "This overnight educational camping adventure is designed for school, scout, and youth groups (grades 3–12). Sleepover activities are aligned with the Next Generation Science Standards. Each sleepover program includes:\n\nOrientation and games with Dr. Zoolittle\n\nLive animal presentations\n\nPrivate bus tour\n\nZoo craft activity\n\nSet up your own Zoo tent and camp at the Zoo’s Camp Timbuktu\n\nS’mores around the campfire\n\nGuided nighttime stroll featuring nocturnal animals\n\nBreakfast and beverages\n\nOptional hot buffet dinner, breakfast, and beverages for an additional fee\n\nExclusive (pre-opening) morning animal viewing with keepers\n\nChoose from the following grade levels/themes:\n\nGrades 3–5: Adaptations and Environments\nGrades 6-8: Natural Selection: Genetic Traits and the Environment\nGrades 9-12: Biodiversity and Human Impact on the Environment\nAny Grade: How Do You Zoo? Exploring Conservation Careers\nAny Grade: Wildlife Heroes Conservation Campout\n\nPrivate sleepover nights are available any day of the year for groups of 35 or more. Please call 619-718-3000 for more information.\n\nAdult/Child Ratio for grades 3-8:\n\nMinimum adult to child ratio of 1:4.\nMaximum adult to child ratio of 1:1.\nAdult/Child Ratio for grades 9-12:\n\nMinimum adult to child ratio of 1:10.\nMaximum adult to child ratio of 1:1.\nSleepover activities are subject to change.",
                     times: "Private sleepover nights are available any day of the year",
                     duration: "Overnight",
                     ageInterest: "Kids, Teens, Tweens",
                     price: "$90 and up",
                     ticketsURL: justCall),
        ZooEducation(title: "Zoo InternQuest",
                     description: "Zoo InternQuest is a program providing San Diego high school juniors and seniors interested in pursuing careers in the life sciences (biology, zoology, human or veterinary medicine, wildlife management, botany, etc.) the opportunity to learn from our experts. Students learn about conservation, pathology, genetics, veterinary medicine, animal behavior, reproductive physiology, ecology, horticulture, and more by visiting the areas where experts in these fields spend their days. Each session, interns visit a variety of professionals at the different San Diego Zoo locations. During their seven-week internship, participants meet at the Zoo, Safari Park, or the Institute for Conservation Research three days a week (Tuesdays, Wednesdays, and Thursdays), from 2:45 to 5:15 p.m. Wednesdays and Thursdays are spent meeting with Zoo professionals.\n\nAfter meeting with Zoo professionals on Wednesdays and Thursdays, interns write their blogs on their own time and submit for editing the following Monday. Tuesdays, interns work on site at the Zoo to finalize editing and to upload their blog posts. Students are responsible for transportation to and from each of the Zoo locations. Zoo InternQuest participants receive the necessary training to create blogs of their experiences, illustrated with digital photos. Interns also communicate with blog followers and Virtual Interns throughout the world.",
                     times: "Tuesdays, Wednesdays, and Thursdays, from 2:45 to 5:15 p.m.",
                     duration: "Seven weeks",
                     ageInterest: "Teens"),
        ZooEducation(imageString:"Kids Wild Night Out_TN",
                     title: "Kids Wild Night Out",
                     description: "Kids! It’s the evening you’ve been waiting for! Join us at the Zoo for a wild night out with Dr. Zoolittle and animal friends. Hang with us for a few hours, and we will meet some amazing animals, create cool Zoo crafts, play games, enjoy a snack, and much more.\n\nA snack and a souvenir gift are included. Children should eat dinner before they arrive, wear comfortable walking shoes, and bring a jacket for our outdoor activities.\n\nSchedule:\n\nSaturday, November 3, 2018\nSaturday, December 1, 2018\nSaturday, December 15, 2018\nSaturday, January 5, 2019\nSaturday, February 2, 2019\nSaturday, March 2, 2019\nSaturday, March 30, 2019\nSaturday, April 6, 2019\nSaturday, May 4, 2019\nSaturday, June 1, 2019",
                     times: "Select Saturdays, 6 to 10 p.m",
                     duration: "4 Hours",
                     ageInterest: "Kids",
                     price: "$37 + admission",
                     ticketsURL: "https://tickets.sandiegozoo.org/webstore/shop/ViewItems.aspx?CG=webstoresdzed&C=sdzedkwno"),
        ZooEducation(title: "Zoo Corps",
                     description: "Zoo Corps is for teens ages 13 through 17 who have an interest in wildlife conservation, education, or public speaking. Members set up discovery stations in the Zoo and use artifacts, biofacts, literature, props, and interactive games to teach Zoo guests about topics like animal care, local San Diego habitats, wildlife conservation, and saving species. Zoo Corps members participate at least once a month. See Zoo Website for more information.",
                     times: "See upcoming meeting times",
                     ageInterest: "Teens",
                     price: "$125"),
        ZooEducation(imageString: "Kinder Programs_TN",
                     title: "Kinder Programs",
                     description: "Trek through the Zoo with your favorite adult to visit some of our favorite animals before the Zoo opens for the day. Once you observe and learn about the animal of the month, you may have the opportunity to do a fun craft, listen to an exciting story, or meet an animal ambassador.\n\nL Is for Lion: November 3 and 17, 2018\n\nK Is for Koala: December 1 and 15, 2018\n\nB Is for Baboon: January 5 and 19, 2019\n\nE Is for Elephant: February 2 and 16, 2019\n\nP Is for Penguin: March 2 and 16, 2019\n\nNote: Animal viewing subject to change. Program runs rain or shine.",
                     times: "8:30 to 10 a.m. on Select Days",
                     duration: "90 minutes",
                     ageInterest: "Preschoolers",
                     price: "$15 & up",
                     ticketsURL: "https://tickets.sandiegozoo.org/webstore/shop/ViewItems.aspx?CG=webstoresdzed&C=sdzedkz"),
        ZooEducation(title: "Children Birthday Parties",
                     description: "Celebrate your child’s birthday with this once-in-a-lifetime Australian adventure!  Children ages 10 and younger will enjoy a special birthday celebration in our Aussie Outback party room, hosted by our knowledgeable and fun-loving Zoo educators!  The birthday bash includes up-close animal presentations and entertainment with the Zoo’s own zany animal researcher, Dr. Zoolittle. Guests will enjoy cheese pizza, soda, and juice for lunch; birthday cake; Zoo decorations; and fun Zoo-themed birthday activities.",
                     ageInterest: "Preschoolers, Kids",
                     price: "$79 per person",
                     ticketsURL: justCall),
        ZooEducation(title: "Assembly & Classroom Programs",
                     description: "Our programs align with the new Next Generation Science and Common Core State Standards. We can bring wildlife, fun, and learning right to your school! Just call 619-557-3963 or 619-557-3962 to reserve an outreach program for your auditorium or classroom.",
                     duration: "50 to 55 minutes",
                     ageInterest: "Kids, Teens, Tweens",
                     price: "$225 and up",
                     ticketsURL: justCall),
        ZooEducation(title: "Field Trips",
                     description: "Admission to the Zoo is FREE for all students in San Diego County during the traditional school year. Non-San Diego County schools and qualified home schools receive a reduced admission fee of $15 per student. All schools and qualified home schools pay $15 per person on weekends, holidays, and during winter, spring and summer school breaks. During October, in-county and out-of-county school groups, grades pre-K–12, are admitted free, but must make a reservation.",
                     duration: "All Day",
                     ageInterest: "Kids, Teens, Tweens",
                     ticketsURL: justCall),
        ZooEducation(title: "Guided Tours",
                     description: """
If you don’t want to be the tour guide, a Zoo Educator can guide your students through the Zoo while enthralling them with inside information. All tours include a bus tour, behind-the-scenes visits, and up-close animal encounters. Our programs align with Next Generation Science and Common Core State Standards, and are complemented by our world-class curriculum that you can implement in your own classroom!

Call 619-557-3963 for Reservations. For Education programs for children, adults, & families, or any school-related programs, please call Zoo Education. For Wildlife Sleepover questions and information only: Call 619-718-3000. See San Diego Zoo Website for more details.
""",
                     ageInterest: "Kids, Teens, Tweens",
                     ticketsURL: justCall)
    ]
    
    static let activities = [
        Activity(title: "Balboa Park Miniature Train",
                 description: "The Balboa Park Miniature Train is operated by the San Diego Zoo. The train pulls out of the station for three-minute rides around a portion of Balboa Park. The train station is located outside the Zoo’s exit. Obtain a hand stamp at the Zoo's exit for same day re-entry. Ages 5 and younger must ride with a paying adult.",
                 times: "Weekends and Holidays, 11 a.m. to 4:30 p.m",
                 ageInterest: "Kids",
                 price: "$3 for ages 1 and older; younger than age 1 is free."),
        Activity(title: "Guided Bus Tour",
                 description: "Enjoy a 35-minute narrated tour on a double-decked bus covering much of the Zoo. The Guided Bus Tour presented by Go San Diego® Card is included with all admission tickets and donor level memberships. \n\nA Spanish version of the 35-minute tour is offered at noon daily. Reservations are required; please inquire at ticket booth. Also available for groups of 20 or more with advance notice.\n\nASL-interpreted tours are available with advance notice. For all guest-interpreting requests, reservations should be made one week in advance of the day of the visit by calling 619-231-1515, ext. 4526.",
                 times: "9:30 a.m. to 5 p.m.",
                 price: "Annual Pass Members pay $13 per adult and $10 per child, ages 3 through 11, for a day of unlimited rides on the Guided Bus Tour and Kangaroo Bus"),
        Activity(title: "Skyfari Aerial Tram",
                 description: "Take an airborne shortcut over the treetops to the other end of the Zoo and enjoy spectacular views of the Zoo, its animal and plant collection, and surrounding Balboa Park (jogging, oversized and double strollers cannot be accommodated; children younger than 8 years old must be accompanied by an adult). Presented by Alaska Airlines®.",
                 times: "10 a.m. to 6 p.m. daily",
                 price: "Free"),
        Activity(title: "Kangaroo Bus",
                 description: "There is so much to see at the Zoo! The Kangaroo Bus lets you hop on and off at four different stops throughout the Zoo. Just wait at one of the stops for a bus with a yellow Kangaroo Bus banner to arrive, about every 15 minutes. All admission tickets, donor level memberships and purchased Guided Bus Tour tickets include the Kangaroo Bus.",
                 times: "10:30 a.m. to 5:30 p.m. daily",
                 price: "Annual Pass Members purchasing only the Kangaroo Bus pay $8 for adults and $6 for children, ages 3 through 11."),
        Activity(title: "4-D Theater West",
                 description: "Happy Feet 4-D takes you on an adventure to Antarctica, where you'll meet a lively cast of penguin characters, including Mumble, a tap-dancing emperor penguin. The Martian 4-D Experience stars Matt Damon as an astronaut stranded on Mars who must use his scientific ingenuity to help him reunite with his crewmates in a daring mission.",
                 times: "Shown daily, 10:30 a.m. to 4 p.m.",
                 price: "$7"),
        Activity(title: "Rio 4-D Theater",
                 description: "Zoom through the rain forest with Blu and Jewel in this special 4-D version of the popular animated film Rio.",
                 times: "Shown daily, 10:30 a.m. to 4 p.m.",
                 price: "$7")
    ]
    
    static let animalEncounters = [
        AnimalEncounter(title: "Keeper Talks: Insects",
                        description: "Learn more about the planet's spineless wonders!",
                        times: "Daily, 11:30 a.m.",
                        location: "Insect House"),
        AnimalEncounter(title: "Petting Paddock",
                        description: "Pet the wooly coat of a sheep or comb a gentle pygmy goat’s hair. ",
                        times: "9:30 a.m. to 5:30 p.m.",
                        location: "Discovery Outpost"),
        AnimalEncounter(title: "Keeper Talks: Lions and Jaguars",
                        description: "Find out more about lions and jaguars.",
                        times: "Times: Daily, 1 p.m.",
                        location: "Elephant Odyssey"),
        AnimalEncounter(title: "Keeper Talks: Children's Zoo Surprise",
                        description: "What fascinating animal will you see today?",
                        times: "Daily, 11:15 a.m.",
                        location: "Children's Zoo"),
        AnimalEncounter(title: "Tasmanian Devil Enrichment",
                        description: "Get a rare look at remarkable, endangered Tasmanian devils at the Zoo's Australian Outback.  ",
                        times: "Daily, Noon",
                        location: "Outback"),
        AnimalEncounter(title: "Animal Encounters",
                        description: "Meet an animal ambassador up close on the Front Plaza Stage. You might even have a closer encounter than you expect!",
                        times: "Daily, 10:30 a.m.",
                        location: "Front Street Stage"),
        AnimalEncounter(title: "Keeper Talks: Sloths",
                        description: "Learn more about this amazing animal with a reputation for living life in the slow lane.",
                        times: "Daily, Noon",
                        location: "Elephant Odyssey"),
        AnimalEncounter(title: "Insect House",
                        description: "Sometimes, the littlest things have the biggest impact. Just down the path from the Children’s Zoo’s Petting Paddock, the Insect House is abuzz with wonder! Terrariums set into the walls showcase stick insects, leafcutter ants, roaches, beetles, scorpions, and spiders, giving you a rare opportunity to marvel at the planet’s spineless wonders.",
                        times: "10 a.m. to 5:30 p.m.",
                        location: "Discovery Outpost"),
        AnimalEncounter(title: "Keeper Talks: Lemurs",
                        description: "Learn more about the lemurs of Africa Rocks.",
                        times: "Daily, 12:45 p.m.",
                        location: "Africa Rocks"),
        AnimalEncounter(title: "Keeper Talks: Baboons",
                        description: "Find out more about Africa Rocks' amazing group of hamadryas baboons. ",
                        times: "Daily, 1:30 p.m.",
                        location: "Africa Rocks"),
        AnimalEncounter(title: "Keeper Talks: Rhinos",
                        description: "Discover more about those remarkable rhinos.",
                        times: "Daily; 3:30 p.m.",
                        location: "Urban Jungle"),
        AnimalEncounter(title: "Animal Encounters: Africa Rocks",
                        description: "Meet an animal ambassador up close at Africa Rocks, near Rocks Box. ",
                        times: "Daily, 10:30 a.m. and 12:30 p.m.",
                        location: "Africa Rocks")
    ]
    
    static let shows = [
        Show(title: "Dr. Zoolittle and Friends Explore Australia",
             description: "Stop by Koalafornia Boardwalk for a show that's fun for the whole family, and meet our Zoo costumed characters!",
             times: "Noon and 1 p.m. Saturdays and Sundays",
             location: "Koalafornia Boardwalk"),
        Show(title: "Wild About Animals",
             description: "Meet our world-famous animal ambassadors and their trainers, and find out why we're Wild About Animals! It's a Zoo tradition, daily at the historic Wegeforth Bowl.",
             times: "Daily at 1 p.m.",
             location: "Wegeforth Bowl")
    ]
    
    static let playAreas = [
        PlayArea(title: "Elephant Play Yard",
                 description: "Across from the condors is an open-air and hands-on play and exploration area for kids and kids at heart. Kids can work off some energy with a maze of elephant satellite tracking collars, a play fossil dig, and puzzles to solve. Located at Elephant Odyssey.",
                 location: "Elephant Odyssey"),
        PlayArea(title: "Discovery Playground",
                 description: "Explore Discovery Playground, located at Discovery Outpost!",
                 location: "Discovery Outpost"),
        PlayArea(title: "Polar Play Area",
                 description: "Get the scoop on polar bears from supersized illustrated storybooks, compare your height to our life-size polar bear statues, and then crawl into a polar bear den and pop your head up through ice holes. Located in Northern Frontier.",
                 location: "Northern Frontier"),
        PlayArea(title: "Koala Klimber",
                 description: "Ever wanted to hang out in the trees with koalas? Well, here’s your opportunity—with our koala replicas, that is. Choose a seat and settle in koala style, and have your photo taken to share with family and friends!",
                 location: "Outback")
    ]
    
}
